git stuff

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -67,11 +67,9 @@ if [[ "$SUPRESS_TTYSPLASH" == "" ]]; then
 	fi
 	if [[ "$(tty)" == "/dev/tty1" ]]; then
 		clear
-		# Wait for the network
-		waitnet 5 api.github.com
 		# Update wezterm (it's an AppImage from GitHub)
 		echo ">>> startup task: Reinstalling WezTerm... <<<"
-		wezterm-reinst
+		ping -c1 api.github.com && wezterm-reinst || echo "Never mind. Cannot access GitHub right now."
 		echo ">>> startup task: Updating nix channels... <<<"
 		nix-channel --update
 		clear
