fix `wezterm-reinst`

diff --git a/bin/wezterm-reinst b/bin/wezterm-reinst
--- a/bin/wezterm-reinst
+++ b/bin/wezterm-reinst
@@ -3,9 +3,18 @@
 LOCATION="$HOME/WezTerm.AppImage"
 REPONAME="wez/wezterm"
 ASSETENDING="Ubuntu18.04.AppImage"
-rm $LOCATION
+rm $LOCATION && echo "Removed WezTerm at $LOCATION. Reinstalling..." || echo "WezTerm not found at $LOCATION. Installing it (hopefully) for the first time..."
+echo "Querying the GitHub API for the latest release (of $REPONAME)..."
 RELEASENAME=`curl --silent "https://api.github.com/repos/$REPONAME/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
-curl -LO "https://github.com/$REPONAME/releases/download/$RELEASENAME/WezTerm-$RELEASENAME-$ASSETENDING"
-mv WezTerm-$RELEASENAME-$ASSETENDING $LOCATION
+INSTALLNAME="WezTerm-$RELEASENAME-$ASSETENDING"
+echo "Got $RELEASENAME, downloading $INSTALLNAME..."
+curl -LO "https://github.com/$REPONAME/releases/download/$RELEASENAME/$INSTALLNAME"
+echo "Downloaded $INSTALLNAME."
+echo "Cleaning up..."
+mv WezTerm-$INSTALLNAME $LOCATION
 chmod +x $LOCATION
+echo "Installed $INSTALLNAME (from $REPONAME)."
+export WEZTERM_INSTALL="$LOCATION"
+echo "Set WEZTERM_INSTALL=$WEZTERM_INSTALL."
+echo "All done."
 
