fix `with-nix-deps`

diff --git a/bin/with-nix-deps b/bin/with-nix-deps
--- a/bin/with-nix-deps
+++ b/bin/with-nix-deps
@@ -6,7 +6,11 @@ else
 	TARGET_CMD="$1"
 fi
 NSDEPS_FILE="$(git rev-parse --show-toplevel)/.nix_shell_deps"
-NSDEPS="$(cat $NSDEPS_FILE)"
-eval "nix-shell -p $NSDEPS --command '$TARGET_CMD'"
-echo $NSDEPS | tr ' ' '\n' | grep '^gh$' >/dev/null && git config --list | grep 'github\.com\.helper' | sed 's/=.*//' | xargs -n 1 git config --global --unset-all
+if [[ -f "$NSDEPS_FILE" ]]; then
+	NSDEPS="$(cat $NSDEPS_FILE)"
+	eval "nix-shell -p $NSDEPS --command '$TARGET_CMD'"
+else
+	echo "Could not find <repo>/.nix_shell_deps, exiting."
+	exit 1
+fi
 
